//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JournalTrace.Language.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JournalTrace.Language.Localization.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity of entries:.
        /// </summary>
        internal static string countall {
            get {
                return ResourceManager.GetString("countall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories:.
        /// </summary>
        internal static string countdirectories {
            get {
                return ResourceManager.GetString("countdirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files:.
        /// </summary>
        internal static string countfiles {
            get {
                return ResourceManager.GetString("countfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldest entry:.
        /// </summary>
        internal static string countfirst {
            get {
                return ResourceManager.GetString("countfirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current file.
        /// </summary>
        internal static string currentfile {
            get {
                return ResourceManager.GetString("currentfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Grid.
        /// </summary>
        internal static string datagrid {
            get {
                return ResourceManager.GetString("datagrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        internal static string directory {
            get {
                return ResourceManager.GetString("directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Tree.
        /// </summary>
        internal static string directorytree {
            get {
                return ResourceManager.GetString("directorytree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive.
        /// </summary>
        internal static string drive {
            get {
                return ResourceManager.GetString("drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter entry directory.
        /// </summary>
        internal static string enterdir {
            get {
                return ResourceManager.GetString("enterdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show file information.
        /// </summary>
        internal static string entryinfo {
            get {
                return ResourceManager.GetString("entryinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was deleted.
        /// </summary>
        internal static string filedeleted {
            get {
                return ResourceManager.GetString("filedeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Identification.
        /// </summary>
        internal static string fileid {
            get {
                return ResourceManager.GetString("fileid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string format {
            get {
                return ResourceManager.GetString("format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive selection.
        /// </summary>
        internal static string formdrive {
            get {
                return ResourceManager.GetString("formdrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry information.
        /// </summary>
        internal static string formentryinfo {
            get {
                return ResourceManager.GetString("formentryinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last modification $UsnJrnl:$J.
        /// </summary>
        internal static string lbUsnJrnl {
            get {
                return ResourceManager.GetString("lbUsnJrnl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idea for the project, translated reasons.
        /// </summary>
        internal static string lordyzagatdesc {
            get {
                return ResourceManager.GetString("lordyzagatdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenByFileId Win32 API wrapper for C#.
        /// </summary>
        internal static string nolandesc {
            get {
                return ResourceManager.GetString("nolandesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main developer.
        /// </summary>
        internal static string poneidesc {
            get {
                return ResourceManager.GetString("poneidesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string reason {
            get {
                return ResourceManager.GetString("reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        internal static string root {
            get {
                return ResourceManager.GetString("root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string scan {
            get {
                return ResourceManager.GetString("scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTFS UsnJournal Win32 API wrapper for C#.
        /// </summary>
        internal static string skipperdesc {
            get {
                return ResourceManager.GetString("skipperdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program couldn&apos;t create a handle to the selected drive, to query the current journal state..
        /// </summary>
        internal static string statusdesc_1 {
            get {
                return ResourceManager.GetString("statusdesc-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program couldn&apos;t query the current state of the journal. Make sure the selected drive has journaling enabled..
        /// </summary>
        internal static string statusdesc_2 {
            get {
                return ResourceManager.GetString("statusdesc-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program couldn&apos;t call DeviceIoControl properly to return all the journal entries in the drive..
        /// </summary>
        internal static string statusdesc_3 {
            get {
                return ResourceManager.GetString("statusdesc-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program couldn&apos;t resolve file ID&apos;s properly. Is something blocking the program?.
        /// </summary>
        internal static string statusdesc_4 {
            get {
                return ResourceManager.GetString("statusdesc-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program couldn&apos;t parse journal entries correctly. This could be the program&apos;s fault..
        /// </summary>
        internal static string statusdesc_5 {
            get {
                return ResourceManager.GetString("statusdesc-5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the desired drive and start filtering journal entries..
        /// </summary>
        internal static string statusdesc0 {
            get {
                return ResourceManager.GetString("statusdesc0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To query the journal, we have to make sure we can create handles to it without problems..
        /// </summary>
        internal static string statusdesc1 {
            get {
                return ResourceManager.GetString("statusdesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to query the current state of the journal to get it&apos;s values..
        /// </summary>
        internal static string statusdesc2 {
            get {
                return ResourceManager.GetString("statusdesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling DeviceIoControl to give us all the entries in the current journal ID..
        /// </summary>
        internal static string statusdesc3 {
            get {
                return ResourceManager.GetString("statusdesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File ID&apos;s aren&apos;t human readable paths, so we need to resolve all the possible ones..
        /// </summary>
        internal static string statusdesc4 {
            get {
                return ResourceManager.GetString("statusdesc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing all journal entries into classes that we will modify and query later..
        /// </summary>
        internal static string statusdesc5 {
            get {
                return ResourceManager.GetString("statusdesc5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a layout type to view the collected data. Each will visualize data on a different way..
        /// </summary>
        internal static string statusdesc6 {
            get {
                return ResourceManager.GetString("statusdesc6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing journal entries to rows....
        /// </summary>
        internal static string statusgrid0 {
            get {
                return ResourceManager.GetString("statusgrid0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding rows to control....
        /// </summary>
        internal static string statusgrid1 {
            get {
                return ResourceManager.GetString("statusgrid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get handle to volume..
        /// </summary>
        internal static string statustitle_1 {
            get {
                return ResourceManager.GetString("statustitle-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get current journal state..
        /// </summary>
        internal static string statustitle_2 {
            get {
                return ResourceManager.GetString("statustitle-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t query journal entries..
        /// </summary>
        internal static string statustitle_3 {
            get {
                return ResourceManager.GetString("statustitle-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t resolve ID&apos;s..
        /// </summary>
        internal static string statustitle_4 {
            get {
                return ResourceManager.GetString("statustitle-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t parse entries..
        /// </summary>
        internal static string statustitle_5 {
            get {
                return ResourceManager.GetString("statustitle-5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting input....
        /// </summary>
        internal static string statustitle0 {
            get {
                return ResourceManager.GetString("statustitle0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting handle to volume....
        /// </summary>
        internal static string statustitle1 {
            get {
                return ResourceManager.GetString("statustitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting current journal state....
        /// </summary>
        internal static string statustitle2 {
            get {
                return ResourceManager.GetString("statustitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Querying journal entries....
        /// </summary>
        internal static string statustitle3 {
            get {
                return ResourceManager.GetString("statustitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolving file ID&apos;s....
        /// </summary>
        internal static string statustitle4 {
            get {
                return ResourceManager.GetString("statustitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing entries....
        /// </summary>
        internal static string statustitle5 {
            get {
                return ResourceManager.GetString("statustitle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All done!.
        /// </summary>
        internal static string statustitle6 {
            get {
                return ResourceManager.GetString("statustitle6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total free space.
        /// </summary>
        internal static string totalfreespace {
            get {
                return ResourceManager.GetString("totalfreespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total size.
        /// </summary>
        internal static string totalsize {
            get {
                return ResourceManager.GetString("totalsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data overwrite,Data extend,Data truncation,Named data overwrite,Named data extend,Named data truncation,File create,File delete,EA Change,Security change,Rename: old name,Rename: new name,Indexable change,Basic info change,Hard link change,Compression change,Encryption change,Object ID change,Reparse point change,Stream change,Close.
        /// </summary>
        internal static string usnreasons {
            get {
                return ResourceManager.GetString("usnreasons", resourceCulture);
            }
        }
    }
}
