//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JournalTrace.Language.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pt {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pt() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JournalTrace.Language.Localization.pt", typeof(pt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpar.
        /// </summary>
        internal static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar.
        /// </summary>
        internal static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade de entradas:.
        /// </summary>
        internal static string countall {
            get {
                return ResourceManager.GetString("countall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diretórios:.
        /// </summary>
        internal static string countdirectories {
            get {
                return ResourceManager.GetString("countdirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivos:.
        /// </summary>
        internal static string countfiles {
            get {
                return ResourceManager.GetString("countfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrada mais antiga:.
        /// </summary>
        internal static string countfirst {
            get {
                return ResourceManager.GetString("countfirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo atual.
        /// </summary>
        internal static string currentfile {
            get {
                return ResourceManager.GetString("currentfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade de dados.
        /// </summary>
        internal static string datagrid {
            get {
                return ResourceManager.GetString("datagrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diretório.
        /// </summary>
        internal static string directory {
            get {
                return ResourceManager.GetString("directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arvore de diretórios.
        /// </summary>
        internal static string directorytree {
            get {
                return ResourceManager.GetString("directorytree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disco.
        /// </summary>
        internal static string drive {
            get {
                return ResourceManager.GetString("drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar no diretório da entrada.
        /// </summary>
        internal static string enterdir {
            get {
                return ResourceManager.GetString("enterdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar informações do arquivo.
        /// </summary>
        internal static string entryinfo {
            get {
                return ResourceManager.GetString("entryinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar.
        /// </summary>
        internal static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo foi deletado.
        /// </summary>
        internal static string filedeleted {
            get {
                return ResourceManager.GetString("filedeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador do arquivo.
        /// </summary>
        internal static string fileid {
            get {
                return ResourceManager.GetString("fileid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato.
        /// </summary>
        internal static string format {
            get {
                return ResourceManager.GetString("format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleção de disco.
        /// </summary>
        internal static string formdrive {
            get {
                return ResourceManager.GetString("formdrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações da entrada.
        /// </summary>
        internal static string formentryinfo {
            get {
                return ResourceManager.GetString("formentryinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lingua.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to última modificação $UsnJrnl:$J.
        /// </summary>
        internal static string lbUsnJrnl {
            get {
                return ResourceManager.GetString("lbUsnJrnl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideia para o projeto, traduziu razões.
        /// </summary>
        internal static string lordyzagatdesc {
            get {
                return ResourceManager.GetString("lordyzagatdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenByFileId Win32 API compatibilização para C#.
        /// </summary>
        internal static string nolandesc {
            get {
                return ResourceManager.GetString("nolandesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desenvolvedor principal.
        /// </summary>
        internal static string poneidesc {
            get {
                return ResourceManager.GetString("poneidesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razão.
        /// </summary>
        internal static string reason {
            get {
                return ResourceManager.GetString("reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raiz.
        /// </summary>
        internal static string root {
            get {
                return ResourceManager.GetString("root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escanear.
        /// </summary>
        internal static string scan {
            get {
                return ResourceManager.GetString("scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar.
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTFS UsnJournal Win32 API compatibilização para C#.
        /// </summary>
        internal static string skipperdesc {
            get {
                return ResourceManager.GetString("skipperdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O programa não conseguiu manejar o disco selecionado, para consultar o estado atual do journal..
        /// </summary>
        internal static string statusdesc_1 {
            get {
                return ResourceManager.GetString("statusdesc-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O programa não conseguiu consultar o estado atual do journal. Certifique-se de que o disco selecionado tenha o journal habilitado..
        /// </summary>
        internal static string statusdesc_2 {
            get {
                return ResourceManager.GetString("statusdesc-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O programa não conseguiu chamar o DeviceIoControl corretamente para retornar todos as entradas do journal do disco..
        /// </summary>
        internal static string statusdesc_3 {
            get {
                return ResourceManager.GetString("statusdesc-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O programa não conseguiu resolver as identificações dos arquivos corretamente. Algo está bloqueando o programa?.
        /// </summary>
        internal static string statusdesc_4 {
            get {
                return ResourceManager.GetString("statusdesc-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O programa não conseguiu analisar corretamente as entradas do journal corretamente. Isto pode ser culpa do programa..
        /// </summary>
        internal static string statusdesc_5 {
            get {
                return ResourceManager.GetString("statusdesc-5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, selecione o disco desejado e incie a filtragem do journal..
        /// </summary>
        internal static string statusdesc0 {
            get {
                return ResourceManager.GetString("statusdesc0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para consultar o journal, temos que ter certeza de que podemos criar handles sem problemas..
        /// </summary>
        internal static string statusdesc1 {
            get {
                return ResourceManager.GetString("statusdesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precisamos consultar o estado atual do journal para obter seus valores..
        /// </summary>
        internal static string statusdesc2 {
            get {
                return ResourceManager.GetString("statusdesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chamando de DeviceIoControl para nos dar todas as entradas do ID do journal atual..
        /// </summary>
        internal static string statusdesc3 {
            get {
                return ResourceManager.GetString("statusdesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os ID&apos;s dos arquivos não são caminhos legíveis por humanos, então precisamos resolver todos os possíveis..
        /// </summary>
        internal static string statusdesc4 {
            get {
                return ResourceManager.GetString("statusdesc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformando todas as entradas de journal em classes que modificaremos e consultaremos mais tarde..
        /// </summary>
        internal static string statusdesc5 {
            get {
                return ResourceManager.GetString("statusdesc5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um tipo de layout para visualizar os dados coletados. Cada um mostrará os dados de uma maneira diferente..
        /// </summary>
        internal static string statusdesc6 {
            get {
                return ResourceManager.GetString("statusdesc6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformando entradas em fileiras....
        /// </summary>
        internal static string statusgrid0 {
            get {
                return ResourceManager.GetString("statusgrid0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionando fileiras à grade....
        /// </summary>
        internal static string statusgrid1 {
            get {
                return ResourceManager.GetString("statusgrid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível manejar o disco selecionado..
        /// </summary>
        internal static string statustitle_1 {
            get {
                return ResourceManager.GetString("statustitle-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível retornar o estado atual do journal..
        /// </summary>
        internal static string statustitle_2 {
            get {
                return ResourceManager.GetString("statustitle-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível consultar as entradas do journal..
        /// </summary>
        internal static string statustitle_3 {
            get {
                return ResourceManager.GetString("statustitle-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível resolver os ID&apos;s..
        /// </summary>
        internal static string statustitle_4 {
            get {
                return ResourceManager.GetString("statustitle-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível analisar as entradas..
        /// </summary>
        internal static string statustitle_5 {
            get {
                return ResourceManager.GetString("statustitle-5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguardando entrada....
        /// </summary>
        internal static string statustitle0 {
            get {
                return ResourceManager.GetString("statustitle0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting handle to volume....
        /// </summary>
        internal static string statustitle1 {
            get {
                return ResourceManager.GetString("statustitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtendo o estado atual do journal....
        /// </summary>
        internal static string statustitle2 {
            get {
                return ResourceManager.GetString("statustitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultando as entradas do journal....
        /// </summary>
        internal static string statustitle3 {
            get {
                return ResourceManager.GetString("statustitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolvendo identificações de arquivos....
        /// </summary>
        internal static string statustitle4 {
            get {
                return ResourceManager.GetString("statustitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analisando entradas....
        /// </summary>
        internal static string statustitle5 {
            get {
                return ResourceManager.GetString("statustitle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tudo pronto!.
        /// </summary>
        internal static string statustitle6 {
            get {
                return ResourceManager.GetString("statustitle6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espaço total livre.
        /// </summary>
        internal static string totalfreespace {
            get {
                return ResourceManager.GetString("totalfreespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espaço total.
        /// </summary>
        internal static string totalsize {
            get {
                return ResourceManager.GetString("totalsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substituição de dados,Extensão de dados,Truncagem de dados,Substituição de dados nomeados,Extensão de dados nomeados,Truncagem de dados nomeados,Criação de arquivo,Exclusão de arquivo,Alteração de EA,Alteração de segurança,Renomear: nome antigo,Renomear: novo nome,Alteração de indexável,Alteração de informações básicas,Alteração de link físico,Alteração de compressão,Alteração de criptografia,Alteração de ID de objeto,Alteração do ponto de nova análise,Alteração de fluxo,Fechar.
        /// </summary>
        internal static string usnreasons {
            get {
                return ResourceManager.GetString("usnreasons", resourceCulture);
            }
        }
    }
}
